// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CopyPath(arg1:string,arg2:string):Promise<boolean>;

export function DeleteFile(arg1:string):Promise<boolean>;

export function DirSize(arg1:string):Promise<number>;

export function GetCwd():Promise<string>;

export function GitAdd(arg1:string):Promise<boolean>;

export function GitCommit(arg1:string,arg2:boolean):Promise<boolean>;

export function GitIgnore(arg1:string):Promise<boolean>;

export function GitLastCommitMessage():Promise<string>;

export function GitPush():Promise<boolean>;

export function GitRevert(arg1:string):Promise<boolean>;

export function GitStatus():Promise<Array<main.GitFileStatus>>;

export function GitUnstage(arg1:string):Promise<boolean>;

export function ListDir(arg1:string):Promise<Array<main.FileEntry>>;

export function ListVolumes():Promise<Array<main.VolumeInfo>>;

export function MovePath(arg1:string,arg2:string):Promise<boolean>;

export function Navigate(arg1:string):Promise<string>;

export function Ping():Promise<string>;

export function PrepareVideoPath(arg1:string):Promise<string>;

export function ReadBinaryFile(arg1:string):Promise<string>;

export function ReadDocxFile(arg1:string):Promise<string>;

export function ReadTextFile(arg1:string):Promise<string>;

export function Rename(arg1:string,arg2:string):Promise<boolean>;

export function WriteTextFile(arg1:string,arg2:string):Promise<boolean>;
