// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanThumbs(arg1, arg2) {
  return window['go']['main']['App']['CleanThumbs'](arg1, arg2);
}

export function ClearDoneTransfers() {
  return window['go']['main']['App']['ClearDoneTransfers']();
}

export function CloseTerminalSession(arg1) {
  return window['go']['main']['App']['CloseTerminalSession'](arg1);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function DirSize(arg1) {
  return window['go']['main']['App']['DirSize'](arg1);
}

export function EnqueueCopy(arg1, arg2) {
  return window['go']['main']['App']['EnqueueCopy'](arg1, arg2);
}

export function EnqueueMove(arg1, arg2) {
  return window['go']['main']['App']['EnqueueMove'](arg1, arg2);
}

export function GemmaMemory() {
  return window['go']['main']['App']['GemmaMemory']();
}

export function GetCwd() {
  return window['go']['main']['App']['GetCwd']();
}

export function GetTransferQueue() {
  return window['go']['main']['App']['GetTransferQueue']();
}

export function GitAdd(arg1) {
  return window['go']['main']['App']['GitAdd'](arg1);
}

export function GitBranchName() {
  return window['go']['main']['App']['GitBranchName']();
}

export function GitBranches() {
  return window['go']['main']['App']['GitBranches']();
}

export function GitCheckoutBranch(arg1) {
  return window['go']['main']['App']['GitCheckoutBranch'](arg1);
}

export function GitCommit(arg1, arg2) {
  return window['go']['main']['App']['GitCommit'](arg1, arg2);
}

export function GitCreateBranch(arg1) {
  return window['go']['main']['App']['GitCreateBranch'](arg1);
}

export function GitDiff(arg1) {
  return window['go']['main']['App']['GitDiff'](arg1);
}

export function GitIgnore(arg1) {
  return window['go']['main']['App']['GitIgnore'](arg1);
}

export function GitLastCommitMessage() {
  return window['go']['main']['App']['GitLastCommitMessage']();
}

export function GitLog() {
  return window['go']['main']['App']['GitLog']();
}

export function GitPush() {
  return window['go']['main']['App']['GitPush']();
}

export function GitRevert(arg1) {
  return window['go']['main']['App']['GitRevert'](arg1);
}

export function GitRoot() {
  return window['go']['main']['App']['GitRoot']();
}

export function GitShow(arg1, arg2) {
  return window['go']['main']['App']['GitShow'](arg1, arg2);
}

export function GitStatus() {
  return window['go']['main']['App']['GitStatus']();
}

export function GitUnstage(arg1) {
  return window['go']['main']['App']['GitUnstage'](arg1);
}

export function LaunchTerminalProfile(arg1) {
  return window['go']['main']['App']['LaunchTerminalProfile'](arg1);
}

export function LaunchTerminalProfileAt(arg1, arg2) {
  return window['go']['main']['App']['LaunchTerminalProfileAt'](arg1, arg2);
}

export function LaunchTerminalProfileAtSized(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LaunchTerminalProfileAtSized'](arg1, arg2, arg3, arg4);
}

export function ListDir(arg1) {
  return window['go']['main']['App']['ListDir'](arg1);
}

export function ListRecursiveFiles(arg1) {
  return window['go']['main']['App']['ListRecursiveFiles'](arg1);
}

export function ListVolumes() {
  return window['go']['main']['App']['ListVolumes']();
}

export function MemoryUsage() {
  return window['go']['main']['App']['MemoryUsage']();
}

export function MkDir(arg1) {
  return window['go']['main']['App']['MkDir'](arg1);
}

export function Navigate(arg1) {
  return window['go']['main']['App']['Navigate'](arg1);
}

export function OllamaChat(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['OllamaChat'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function PathIsDir(arg1) {
  return window['go']['main']['App']['PathIsDir'](arg1);
}

export function Ping() {
  return window['go']['main']['App']['Ping']();
}

export function PreparePdfThumb(arg1) {
  return window['go']['main']['App']['PreparePdfThumb'](arg1);
}

export function PrepareVideoPath(arg1) {
  return window['go']['main']['App']['PrepareVideoPath'](arg1);
}

export function ReadBinaryFile(arg1) {
  return window['go']['main']['App']['ReadBinaryFile'](arg1);
}

export function ReadDocxFile(arg1) {
  return window['go']['main']['App']['ReadDocxFile'](arg1);
}

export function ReadPandocHtml(arg1) {
  return window['go']['main']['App']['ReadPandocHtml'](arg1);
}

export function ReadTextFile(arg1) {
  return window['go']['main']['App']['ReadTextFile'](arg1);
}

export function Rename(arg1, arg2) {
  return window['go']['main']['App']['Rename'](arg1, arg2);
}

export function RenameTerminalSession(arg1, arg2) {
  return window['go']['main']['App']['RenameTerminalSession'](arg1, arg2);
}

export function ResizeTerminalSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminalSession'](arg1, arg2, arg3);
}

export function SendTerminalInput(arg1, arg2) {
  return window['go']['main']['App']['SendTerminalInput'](arg1, arg2);
}

export function TerminalCount() {
  return window['go']['main']['App']['TerminalCount']();
}

export function TerminalProfileUsage(arg1) {
  return window['go']['main']['App']['TerminalProfileUsage'](arg1);
}

export function TerminalProfiles() {
  return window['go']['main']['App']['TerminalProfiles']();
}

export function TerminalSessions() {
  return window['go']['main']['App']['TerminalSessions']();
}

export function WriteTextFile(arg1, arg2) {
  return window['go']['main']['App']['WriteTextFile'](arg1, arg2);
}

export function WriteThumb(arg1, arg2) {
  return window['go']['main']['App']['WriteThumb'](arg1, arg2);
}
