// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseTerminalSession(arg1) {
  return window['go']['main']['App']['CloseTerminalSession'](arg1);
}

export function CopyPath(arg1, arg2) {
  return window['go']['main']['App']['CopyPath'](arg1, arg2);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function DirSize(arg1) {
  return window['go']['main']['App']['DirSize'](arg1);
}

export function GetCwd() {
  return window['go']['main']['App']['GetCwd']();
}

export function GitAdd(arg1) {
  return window['go']['main']['App']['GitAdd'](arg1);
}

export function GitCommit(arg1, arg2) {
  return window['go']['main']['App']['GitCommit'](arg1, arg2);
}

export function GitIgnore(arg1) {
  return window['go']['main']['App']['GitIgnore'](arg1);
}

export function GitLastCommitMessage() {
  return window['go']['main']['App']['GitLastCommitMessage']();
}

export function GitPush() {
  return window['go']['main']['App']['GitPush']();
}

export function GitRevert(arg1) {
  return window['go']['main']['App']['GitRevert'](arg1);
}

export function GitStatus() {
  return window['go']['main']['App']['GitStatus']();
}

export function GitUnstage(arg1) {
  return window['go']['main']['App']['GitUnstage'](arg1);
}

export function LaunchTerminalProfile(arg1) {
  return window['go']['main']['App']['LaunchTerminalProfile'](arg1);
}

export function LaunchTerminalProfileAt(arg1, arg2) {
  return window['go']['main']['App']['LaunchTerminalProfileAt'](arg1, arg2);
}

export function LaunchTerminalProfileAtSized(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LaunchTerminalProfileAtSized'](arg1, arg2, arg3, arg4);
}

export function ListDir(arg1) {
  return window['go']['main']['App']['ListDir'](arg1);
}

export function ListVolumes() {
  return window['go']['main']['App']['ListVolumes']();
}

export function MovePath(arg1, arg2) {
  return window['go']['main']['App']['MovePath'](arg1, arg2);
}

export function Navigate(arg1) {
  return window['go']['main']['App']['Navigate'](arg1);
}

export function Ping() {
  return window['go']['main']['App']['Ping']();
}

export function PrepareVideoPath(arg1) {
  return window['go']['main']['App']['PrepareVideoPath'](arg1);
}

export function ReadBinaryFile(arg1) {
  return window['go']['main']['App']['ReadBinaryFile'](arg1);
}

export function ReadDocxFile(arg1) {
  return window['go']['main']['App']['ReadDocxFile'](arg1);
}

export function ReadPandocHtml(arg1) {
  return window['go']['main']['App']['ReadPandocHtml'](arg1);
}

export function ReadTextFile(arg1) {
  return window['go']['main']['App']['ReadTextFile'](arg1);
}

export function Rename(arg1, arg2) {
  return window['go']['main']['App']['Rename'](arg1, arg2);
}

export function RenameTerminalSession(arg1, arg2) {
  return window['go']['main']['App']['RenameTerminalSession'](arg1, arg2);
}

export function ResizeTerminalSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminalSession'](arg1, arg2, arg3);
}

export function SendTerminalInput(arg1, arg2) {
  return window['go']['main']['App']['SendTerminalInput'](arg1, arg2);
}

export function TerminalCount() {
  return window['go']['main']['App']['TerminalCount']();
}

export function TerminalProfileUsage(arg1) {
  return window['go']['main']['App']['TerminalProfileUsage'](arg1);
}

export function TerminalProfiles() {
  return window['go']['main']['App']['TerminalProfiles']();
}

export function TerminalSessions() {
  return window['go']['main']['App']['TerminalSessions']();
}

export function WriteTextFile(arg1, arg2) {
  return window['go']['main']['App']['WriteTextFile'](arg1, arg2);
}
