// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyPath(arg1, arg2) {
  return window['go']['main']['App']['CopyPath'](arg1, arg2);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function GetCwd() {
  return window['go']['main']['App']['GetCwd']();
}

export function GitAdd(arg1) {
  return window['go']['main']['App']['GitAdd'](arg1);
}

export function GitCommit(arg1, arg2) {
  return window['go']['main']['App']['GitCommit'](arg1, arg2);
}

export function GitIgnore(arg1) {
  return window['go']['main']['App']['GitIgnore'](arg1);
}

export function GitLastCommitMessage() {
  return window['go']['main']['App']['GitLastCommitMessage']();
}

export function GitPush() {
  return window['go']['main']['App']['GitPush']();
}

export function GitRevert(arg1) {
  return window['go']['main']['App']['GitRevert'](arg1);
}

export function GitStatus() {
  return window['go']['main']['App']['GitStatus']();
}

export function GitUnstage(arg1) {
  return window['go']['main']['App']['GitUnstage'](arg1);
}

export function ListDir(arg1) {
  return window['go']['main']['App']['ListDir'](arg1);
}

export function ListVolumes() {
  return window['go']['main']['App']['ListVolumes']();
}

export function MovePath(arg1, arg2) {
  return window['go']['main']['App']['MovePath'](arg1, arg2);
}

export function Navigate(arg1) {
  return window['go']['main']['App']['Navigate'](arg1);
}

export function Ping() {
  return window['go']['main']['App']['Ping']();
}

export function ReadBinaryFile(arg1) {
  return window['go']['main']['App']['ReadBinaryFile'](arg1);
}

export function ReadDocxFile(arg1) {
  return window['go']['main']['App']['ReadDocxFile'](arg1);
}

export function ReadTextFile(arg1) {
  return window['go']['main']['App']['ReadTextFile'](arg1);
}

export function Rename(arg1, arg2) {
  return window['go']['main']['App']['Rename'](arg1, arg2);
}

export function WriteTextFile(arg1, arg2) {
  return window['go']['main']['App']['WriteTextFile'](arg1, arg2);
}
