// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {backend} from '../models';

export function CleanThumbs(arg1:string,arg2:Array<string>):Promise<void>;

export function ClearDoneTransfers():Promise<void>;

export function CloseTerminalSession(arg1:string):Promise<boolean>;

export function DeleteFile(arg1:string):Promise<boolean>;

export function DirSize(arg1:string):Promise<number>;

export function EnqueueCopy(arg1:string,arg2:string):Promise<void>;

export function EnqueueMove(arg1:string,arg2:string):Promise<void>;

export function GemmaMemory():Promise<main.GemmaMemoryInfo>;

export function GetCwd():Promise<string>;

export function GetTransferQueue():Promise<Array<main.TransferJob>>;

export function GitAdd(arg1:string):Promise<boolean>;

export function GitBranchName():Promise<string>;

export function GitBranches():Promise<Array<string>>;

export function GitCheckoutBranch(arg1:string):Promise<boolean>;

export function GitCommit(arg1:string,arg2:boolean):Promise<boolean>;

export function GitCreateBranch(arg1:string):Promise<boolean>;

export function GitDiff(arg1:string):Promise<string>;

export function GitIgnore(arg1:string):Promise<boolean>;

export function GitLastCommitMessage():Promise<string>;

export function GitLog():Promise<string>;

export function GitPush():Promise<boolean>;

export function GitRevert(arg1:string):Promise<boolean>;

export function GitRoot():Promise<string>;

export function GitShow(arg1:string,arg2:string):Promise<string>;

export function GitStatus():Promise<Array<main.GitFileStatus>>;

export function GitUnstage(arg1:string):Promise<boolean>;

export function LaunchTerminalProfile(arg1:string):Promise<string>;

export function LaunchTerminalProfileAt(arg1:string,arg2:string):Promise<string>;

export function LaunchTerminalProfileAtSized(arg1:string,arg2:string,arg3:number,arg4:number):Promise<string>;

export function ListDir(arg1:string):Promise<Array<main.FileEntry>>;

export function ListRecursiveFiles(arg1:string):Promise<Array<main.FileEntry>>;

export function ListVolumes():Promise<Array<main.VolumeInfo>>;

export function MemoryUsage():Promise<Record<string, number>>;

export function MkDir(arg1:string):Promise<boolean>;

export function Navigate(arg1:string):Promise<string>;

export function OllamaChat(arg1:string,arg2:Array<main.OllamaChatMsg>,arg3:Array<string>,arg4:string,arg5:string,arg6:Array<string>):Promise<void>;

export function PathIsDir(arg1:string):Promise<boolean>;

export function Ping():Promise<string>;

export function PreparePdfThumb(arg1:string):Promise<string>;

export function PrepareVideoPath(arg1:string):Promise<string>;

export function ReadBinaryFile(arg1:string):Promise<string>;

export function ReadDocxFile(arg1:string):Promise<string>;

export function ReadPandocHtml(arg1:string):Promise<string>;

export function ReadTextFile(arg1:string):Promise<string>;

export function Rename(arg1:string,arg2:string):Promise<boolean>;

export function RenameTerminalSession(arg1:string,arg2:string):Promise<boolean>;

export function ResizeTerminalSession(arg1:string,arg2:number,arg3:number):Promise<boolean>;

export function SendTerminalInput(arg1:string,arg2:string):Promise<boolean>;

export function TerminalCount():Promise<number>;

export function TerminalProfileUsage(arg1:string):Promise<string>;

export function TerminalProfiles():Promise<Array<backend.TerminalProfile>>;

export function TerminalSessions():Promise<Array<main.TerminalSessionInfo>>;

export function WriteTextFile(arg1:string,arg2:string):Promise<boolean>;

export function WriteThumb(arg1:string,arg2:string):Promise<boolean>;
